# Generated by Django 2.0.1 on 2018-02-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180201_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
