# Generated by Django 2.0.1 on 2018-02-01 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180201_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 8, 9, 8, 747335), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 8, 9, 8, 747354), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 8, 9, 8, 749266), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 8, 9, 8, 749284), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 8, 9, 8, 751602), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 8, 9, 8, 751619), verbose_name='Updated'),
        ),
    ]
