# Generated by Django 2.0.1 on 2018-02-02 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180202_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 10, 8, 3, 647186), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 10, 8, 3, 647206), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 10, 8, 3, 649269), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 10, 8, 3, 649293), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 10, 8, 3, 651764), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 10, 8, 3, 651781), verbose_name='Updated'),
        ),
    ]
