# Generated by Django 2.0.1 on 2018-02-01 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20180201_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='avatar',
            field=models.ImageField(default='/Users/varis.bhalala/Desktop/digi_repository/static/img/dummy.jpg', upload_to='advertiser'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 11, 0, 20, 473526), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 11, 0, 20, 473546), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='avatar',
            field=models.ImageField(default='/Users/varis.bhalala/Desktop/digi_repository/static/img/dummy.jpg', upload_to='publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 11, 0, 20, 475600), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 11, 0, 20, 475617), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 11, 0, 20, 478050), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 11, 0, 20, 478068), verbose_name='Updated'),
        ),
    ]
